description: Push and execute malware via SSM on EC2 instances.
name: SSM Malware Deployment
steps:
- action: aws ssm send-command --document-name 'AWS-RunShellScript' --parameters 'commands=<cmd>'
  description: Execute command remotely
