name: Obsidian Protocol CI

on: [push, pull_request]

jobs:
  test:
    name: Run Tests for ${{ matrix.provider }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        provider: [aws, azure, gcp, oracle, alibaba]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run provider-specific tests
        run: PYTHONPATH=. pytest tests/test_${{ matrix.provider }}.py

      - name: Run proxy compatibility test
        run: PYTHONPATH=. pytest tests/test_${{ matrix.provider }}.py
        env:
          HTTP_PROXY: "http://localhost:8080"
          HTTPS_PROXY: "https://localhost:8443"
          NO_PROXY: "localhost,127.0.0.1"

      - name: Run TTP command tests
        run: PYTHONPATH=. pytest tests/test_ttp_commands.py

  validate:
    name: Validate YAML Files
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install PyYAML
        run: pip install pyyaml

      - name: Validate YAML files
        run: |
          for f in $(find ttps/ scenarios/ -name "*.yaml"); do
            python -c "import yaml, sys; yaml.safe_load(open(sys.argv[1]))" "$f"
          done

      - name: Validate config schema
        run: python scripts/validate_config.py

  archive:
    name: Archive Logs
    runs-on: ubuntu-latest
    needs: [test, validate]
    if: always()
    steps:
      - uses: actions/checkout@v3

      - name: Upload test logs
        uses: actions/upload-artifact@v3
        with:
          name: simulation-logs
          path: logs/

      - name: Upload config and debug artifacts
        uses: actions/upload-artifact@v3
        with:
          name: config-and-debug
          path: |
            config.yaml
            debug/